config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'converter#word'

  get '/word', to: 'converter#word'
  get '/translate', to: 'converter#translate'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/converter_controller.rb
class ConverterController < ApplicationController

  def word
  # Input the word
  # Send to translate
  end

  def translate
  # Do the translation
    word = params[:word]
    leet_array = []
    word.downcase.split("").each do |letter|
      if letter == "a"
        leet_array << "4"
      elsif letter == "b"
        leet_array << '8'
      elsif letter == "e"
        leet_array << "3"
      elsif letter == "g"
        leet_array << "6"
      elsif letter == "i"
        leet_array << "1"
      elsif letter == "l"
        leet_array << "|"
      elsif letter == "o"
        leet_array << "0"
      elsif letter == "s"
        leet_array << "5"
      elsif letter == "t"
        leet_array << "7"
      else
        leet_array <<letter
        end
      end
    @translation = leet_array.join("")

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/converter_helper.rb
module ConverterHelper
end

app/views/converter/translate.html.erb
<div class="container text-center">
  <h1>Your L337 word is:</h1>
  <h2><%= @translation%></h2>
</div>

app/views/converter/word.html.erb
<div class="container text-center">
  <h1>Leet Phrase Translator</h1>
  <h3>Please input the word:</h3>
    <form action="<%= translate_path %>" method="GET">
      <div class="form-group">
        <label for="text">Your text:</label>
        <input type="text" name="word" class="form-control" id="word">
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LeetConverter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>